export const MESSAGES = [
  '1. 我們 wǒmen (ủa mân)Chúng tôi.',
  '2. 什麼 shénme (sấn mơ)Cái gì, hả.',
  '3. 知道 zhīdào (trư tao)Biết, hiểu, rõ.',
  '4. 他們 tāmen (tha mân)Bọn họ.',
  '5. 一個 yīgè (ý cừa)Một cái, một.',
  '6. 你們 nǐmen (nỉ mân)Các bạn',
  '7. 沒有 méiyǒu (mấy yểu)Không có, không bằng, chưa.',
  '8. 這個 zhège (trưa cơ)Cái này, việc này.',
  '9. 怎麼 zěnme (chẩn mơ)Thế nào, sao, như thế.',
  '10. 現在 xiànzài (xien chai)Bây giờ.',
  '11. 可以 kěyǐ (khứa ỷ)Có thể.',
  '12. 如果 rúguǒ (rú cuổ)Nếu.',
  '13. 這樣 zhèyàng (trưa dang)Như vậy, thế này.',
  '14. 告訴 gàosù (cao su)Nói với, tố cáo, tố giác.',
  '15. 因為 yīnwèi (in guây)Bởi vì, bởi rằng.',
  '16. 自己 zìjǐ (chư chỉ)Tự mình, mình.',
  '17. 這裡 zhèlǐ (trưa lỉ)Ở đây.',
  '18. 但是 dànshì (tan sư)Nhưng, mà.',
  '19. 時候 shíhòu (sứ hâu)Thời gian, lúc, khi.',
  '20. 已經 yǐjīng (ỷ ching)Đã, rồi.',
  '21. 謝謝 xièxie (xiê xiệ)Cám ơn.',
  '22. 覺得 juéde (chuế tứa)Cảm thấy, thấy rằng.',
  '23. 這麼 zhème (trưa mơ)Như thế, như vậy, thế này.',
  '24. 先生 xiānsheng (xien sâng)Thầy, tiên sinh, chồng.',
  '25. 喜歡 xǐhuān (xỉ hoan)Thích, vui mừng.',
  '26. 可能 kěnéng (khửa nấng)Có thể, khả năng, chắc là.',
  '27. 需要 xūyào (xuy deo)Cần, yêu cầu.',
  '28. 是的 shì de (sư tợ)Tựa như, giống như.',
  '29. 那麼 nàme (na mờ)Như thế.',
  '30. 那個 nàgè (na cừa)Cái đó, việc ấy, ấy…',
  '31. 東西 dōngxi(tung xi)Đông tây, đồ vật.',
  '32. 應該 yīnggāi (ing cai)Nên, cần phải.',
  '33. 孩子 háizi (hái chự)Trẻ con, con cái.',
  '34. 起來 qǐlái (chỉ lái)Đứng dậy, nổi dậy, vùng lên.',
  '35. 所以 suǒyǐ (suố ỷ)Cho nên, sở dĩ, nguyên cớ.',
  '36. 這些 zhèxiē (trưa xiê)Những…này.',
  '37. 還有 hái yǒu (hái yểu)Vẫn còn.',
  '38. 問題 wèntí (uân thí)Vấn đề, câu hỏi.',
  '39. 一起 yīqǐ (yi chỉ)Cùng nơi, cùng, tổng cộng.',
  '40. 開始 kāishǐ (khai sử)Bắt đầu, lúc đầu.',
  '41. 時間 shíjiān (sứ chen)Thời gian, khoảng thời gian.',
  '42. 工作 gōngzuò (cung chua)Công việc, công tác.',
  '43. 然後 ránhòu (rán hâu)Sau đó, tiếp đó.',
  '44. 一樣 yīyàng (ý dang)Giống nhau, cũng thế.',
  '45. 事情 shìqíng (sư chính)Sự việc, sự tình.',
  '46. 就是 jiùshì (chiêu sư)Nhất định, đúng, dù cho.',
  '47. 所有 suǒyǒu (suố yểu)Sở hữu, tất cả, toàn bộ.',
  '48. 一下 yīxià (ý xia)Một tý, thử xem, bỗng chốc.',
  '49. 非常 fēicháng (phây cháng)Bất thường, rất, vô cùng.',
  '50. 看到 kàn dào (khan tao)Nhìn thấy.',
  '51. 希望 xīwàng (xi oang)Mong muốn, hy vọng, ước ao.',
  '52. 那些 nàxiē (na xiê)Những…ấy, những…đó, những…kia.',
  '53. 當然 dāngrán (tang rán)Đương nhiên, tất nhiên, dĩ nhiên.',
  '54. 也許 yěxǔ (diế xủy)Có lẽ, e rằng, biết đâu.',
  '55. 朋友 péngyǒu (phấng yểu)Bạn bè, bằng hữu.',
  '56. 媽媽 māmā (ma ma)Mẹ, má, u, bầm, bà già.',
  '57. 相信 xiāngxìn (xieng xin)Tin tưởng, tin.',
  '58. 認為 rènwéi (rân uấy)Cho rằng, cho là.',
  '59. 這兒 zhè’er (trưa ơr)Ở đây, chỗ này, lúc này, bây giờ',
  '60. 今天 jīntiān (chin then)Ngày hôm nay, hôm nay, hiện tại,',
  '61. 明白 míngbái (mính bái)Rõ ràng, công khai, hiểu biết.',
  '62. 一直 yīzhí (yi trứ)Thẳng, luôn luôn, liên tục.',
  '63. 看看 kàn kàn (khan khan)Xem xét, xem.',
  '64. 地方 dìfang (ti phang)Địa phương, bản xứ, vùng, miền.',
  '65. 不過 bùguò (pú cua)Cực kỳ, nhất trên đời, nhưng, nhưng',
  '66. 發生 fāshēng (pha sâng)Sinh ra, xảy ra, sản sinh.',
  '67. 回來 huílái (huấy lái)Trở về, quay về.',
  '68. 準備 zhǔnbèi (truẩn bây)Chuẩn bị, dự định.',
  '69. 找到 zhǎodào (trảo tao)Tìm thấy.',
  '70. 爸爸 bàba (pa pa)Bố, cha, ông già.',
  '71. 一切 yīqiè (ý chiê)Tất cả, hết thảy, toàn bộ.',
  '72. 抱歉 bàoqiàn (pao chen)Không phải, ân hận, có lỗi.',
  '73. 感覺 gǎnjué (cản chuế)Cảm giác, cảm thấy, cho rằng.',
  '74. 只是 zhǐshì (trử sư)Chỉ là, chẳng qua là, chỉ, nhưng.',
  '75. 出來 chūlái (chu lái)Đi ra, ra đây, xuất hiện, nảy ra.',
  '76. 不要 bùyào (pú deo)Đừng, không được, chớ.',
  '77. 離開 líkāi (lí khai)Rời khỏi, tách khỏi, ly khai.',
  '78. 一點 yī diǎn (yi tẻn)Một chút, một ít, chút xíu, chút ít.',
  '79. 一定 yī dìng (ý ting)Chính xác, cần phải, nhất định.',
  '80. 還是 háishì (hái sư)Vẫn, vẫn còn, không ngờ, hoặc.',
  '81. 發現 fāxiàn (phan xen)Phát hiện, tìm ra, phát giác.',
  '82. 而且 érqiě (ớ chiể)Mà còn, với lại.',
  '83. 必須 bìxū (pi xuy)Nhất định phải, nhất thiết phải.',
  '84. 意思 yìsi (yi sư)Ý, ý nghĩa.',
  '85. 不錯 bùcuò (pú chua)Đúng, đúng vậy, không tệ.',
  '86. 肯定 kěndìng (khẩn ting)Khẳng định, quả quyết, chắc chắn.',
  '87. 電話 diàn huà (ten hoa)Máy điện thoại, điện thoại.',
  '88. 為了 wèile (guây lơ)Để, vì (biểu thị mục đích).',
  '89. 第一 dì yī (ti yi)Thứ nhất, hạng nhất, quan trọng nhất.',
  '90. 那樣 nàyàng (na dang)Như vậy, như thế.',
  '91. 大家 dàjiā (ta chea)Cả nhà, mọi người.',
  '92. 一些 yīxiē (y xiê)Một ít, một số, hơi, một chút.',
  '93. 那裡 nàlǐ (na lỉ)Chỗ ấy, chỗ đó, nơi ấy.',
  '94. 以為 yǐwéi (ỷ guấy)Tin tưởng, cho rằng.',
  '95. 高興 gāoxìng (cao xing)Vui vẻ, vui mừng, phấn chấn, thích.',
  '96. 過來 guòlái (cua lái)Đủ, quá, đến, qua đây.',
  '97. 等等 děng děng (tấng tẩng)Vân…vân, chờ một chút.',
  '98. 生活 shēnghuó (sâng huố)Đời sống, cuộc sống, sinh hoạt.',
  '99. 醫生 yīshēng (y sâng)Bác sĩ, thày thuốc.',
  '100. 最後 zuìhòu (chuây hâu)Cuối cùng, sau cùng.',
  '101. 之前 zhīqián (trư chén)Trước, trước khi (time).',
  '102. 伙計 huǒjì (huổ chi)Người cộng tác, bạn cùng nghề, làm',
  '103. 任何 rènhé (rân hứa)Bất luận cái gì.',
  '104. 很多 hěnduō (hẩn tuô)Rất nhiều.',
  '105. 哪兒 nǎ’er (nả ớr)Chỗ nào, đâu.',
  '106. 這種 zhè zhǒng (trưa trủng)Kiểu này, loại này.',
  '107. 上帝 shàngdì (sang ti)Thượng đế, chúa trời.',
  '108. 女人 nǚrén (nủy rấn)Phụ nữ, đàn bà (ng trưởng thành).',
  '109. 名字 míngzì (míng chự)Tên (người, sự vật).',
  '110. 認識 rènshi (rân sư)Nhận biết, biết, nhận thức.',
  '111. 今晚 jīn wǎn (chin oản)Tối nay.',
  '112. 其他 qítā (chí tha)Cái khác, khác.',
  '113. 記得 jìdé (chi tứa)Nhớ, nhớ lại, còn nhớ.',
  '114. 傢伙 jiāhuo (chea huô)Cái thứ, thằng cha, cái con.',
  '115. 或者 huòzhě (huô trửa)Có lẽ, hoặc, hoặc là.',
  '116. 過去 guòqù (cuô chuy)Đã qua, đi qua',
  '117. 哪裡 nǎlǐ (ná lỉ)Đâu, nơi nảo, đâu có, đâu phải.',
  '118. 擔心 dānxīn (tan xin)Lo lắng, không yên tâm, lo âu.',
  '119. 繼續 jìxù (chi xuy)Tiếp tục, kéo dài, kế thừa, tiếp nối.',
  '120. 女孩 nǚhái (nủy hái)Cô gái.',
  '121. 親愛 qīn’ài (chin ai)Thân ái, thân thiết, thương yêu.',
  '122. 下來 xiàlái (xia lái)Xuống, lại, tiếp.',
  '123. 父親 fùqīn (phu chin)Phụ thân, bố, cha, ba.',
  '124. 以前 yǐqián (ỷ chén)Trước đây, trước kiam ngày trước.',
  '125. 美國 měiguó (mẩy cuố)Nước Mỹ',
  '126. 完全 wánquán (oán choén)Đầy đủ, trọn vẹn, hoàn toàn.',
  '127. 寶貝 bǎobèi (pảo pây)Bảo bối, cục cưng, của báu.',
  '128. 可是 kěshì (khửa sư)Nhưng, thế nhưng, thật là.',
  '129. 世界 shìjiè (sư chiê)Thế giới, vũ trụ, trái đất.',
  '130. 小時 xiǎoshí (xẻo sứ)Tiếng đồng hồ, giờ.',
  '131. 重要 zhòngyào (trung deo)Trọng yếu, quan trọng.',
  '132. 別人 biérén (biế rấn)Người khác, người ta.',
  '133. 男人 nánrén (nán rấn)Đàn ông, nam nhân.',
  '134. 機會 jīhuì (chi huây)Cơ hội, dịp, thời cơ.',
  '135. 出去 chūqù (chu chuy)Ra, ra ngoài.',
  '136. 看見 kànjiàn (khan chen)Thấy, trông thấy, nhìn thấy.',
  '137. 好像 hǎoxiàng (hảo xieng)Hình như, na ná, giống như.',
  '138. 得到 dédào (tứa tao)Đạt được, nhận được.',
  '139. 警察 jǐngchá (chỉng chá)Cảnh sát.',
  '140. 兒子 érzi (ớ chự)Con trai, người con.',
  '141. 之後 zhīhòu (trư hâu)Sau, sau khi.',
  '142. 漂亮 piàoliang (pheo lieng)Đẹp, xinh xắn.',
  '143. 分鐘 fēnzhōng (phân trung)Phút',
  '144. 再見 zàijiàn (chai chen)Tạm biệt, chào tạm biệt.',
  '145. 如何 rúhé (rú hứa)Làm sao, ntn, ra sao.',
  '146. 比賽 bǐsài (pỉ sai)Thi đấu, đấu.',
  '147. 情況 qíngkuàng (chính khoang)Tình hình, tình huống.',
  '148. 關係 guānxì (quan xi)Quan hệ, liên quan đến.',
  '149. 真是 zhēnshi (trân sư)Rõ là, thật là (không hài lòng)',
  '150. 女士 nǚshì (nủy sư)Nữ sĩ, bà, phu nhân (ngoại giao).',
  '151. 馬上 mǎshàng (mả sang)Lập tức, tức khắc.',
  '152. 決定 juédìng (chuế ting)Quyết định.',
  '153. 見到 jiàn dào (chien tao)Nhìn thấy, gặp mặt.',
  '154. 根本 gēnběn (cân pẩn)Căn bản, chủ yếu, trước giờ.',
  '155. 關於 guānyú (quan úy)Về…',
  '156. 那兒 nà’er (na r)Chỗ ấy, nơi ấy, lúc ấy, bây giờ.',
  '157. 只要 zhǐyào (trử deo)Chỉ cần, miễn là.',
  '158. 裡面 lǐmiàn (lỉ mien)Bên trong, trong.',
  '159. 到底 dàodǐ (tao tỉ)Đến cùng, rốt cuộc, tóm lại.',
  '160. 了解 liǎojiě (léo chiể)Hiểu rõ, biết rõ, hỏi thăm.',
  '161. 明天 míngtiān (míng then)Ngày mai, mai đây.',
  '162. 結束 jiéshù (chiế su)Kết thúc, chấm dứt.',
  '163. 公司 gōngsī (cung sư)Công ty, hãng.',
  '164. 成為 chéngwéi (chấng uấy)Trở thành, biến thành.',
  '165. 永遠 yǒngyuǎn (dúng cản)Vĩnh viễn, mãi mãi.',
  '166. 幫助 bāngzhù (pang tru)Giúp đỡ, viện trợ.',
  '167. 來說 lái shuō (lái suô)…mà nói.',
  '168. 多少 duōshǎo (tuô sảo)Nhiều ít, bao nhiêu, mấy.',
  '169. 它們 tāmen (tha mân)Bọn họ, chúng nó.',
  '170. 確定 quèdìng (chuê ting)Xác định, khẳng định.',
  '171. 有人 yǒurén (yểu rấn)Có người, có ai…',
  '172. 清楚 qīngchǔ (ching chủ)Rõ ràng, tinh tường, hiểu rõ.',
  '173. 晚上 wǎnshàng (oản sang)Buổi tối, ban đêm.',
  '174. 安全 ānquán (an choén)An toàn.',
  '175. 怎樣 zěnyàng (chẩn dang)Thế nào, ra sao.',
  '176. 回家 huí jiā (huấy chea)Về nhà, go home.',
  '177. 願意 yuànyì (doen yi)Vui lòng, bằng lòng, hy vọng.',
  '178. 計劃 jìhuà (chi hoa)Kế hoạch, lập kế hoạch.',
  '179. 不能 bùnéng (pu nấng)Không thể, không được.',
  '180. 說話 shuōhuà (suô hoa)Nói chuyện, trò chuyện, lời nói.',
  '181. 她們 tāmen (tha mân)Họ, bọn họ.',
  '182. 有些 yǒuxiē (yểu xiê)Có một số, một ít,vài phần.',
  '183. 感謝 gǎnxiè (cản xiê)Cảm tạ, cảm ơn.',
  '184. 談談 tán tán (thán thán)Bàn về,thảo luận.',
  '185. 以後 yǐhòu (ỷ hâu)Sau đó, về sau, sau này.',
  '186. 照片 zhàopiàn (trao phien)Bức ảnh, bức hình.',
  '187. 每個 měi gè (mẩy cừa)Mỗi cái',
  '188. 歡迎 huānyíng (hoan ính)Hoan nghênh, chào mừng.',
  '189. 兄弟 xiōngdì (xung ti)Huynh đệ, anh em.',
  '190. 從來 cónglái (chúng lái)Chưa hề, từ trước tới nay.',
  '191. 總是 zǒng shì (chủng sư)Luôn luôn , lúc nào cũng.',
  '192. 拜託 bàituō (pai thuô)Xin nhờ, kính nhờ.',
  '193. 女兒 nǚ’ér (nủy ớ)Con gái.',
  '194. 小姐 xiǎojiě (xéo chiể)Tiểu thư, cô.',
  '195. 消息 xiāoxī (xeo xi)Tin tức, thông tin.',
  '196. 或許 huòxǔ (huô xủy)Có thể, có lẽ, hay là.',
  '197. 如此 rúcǐ (rú chử)Như thế, như vậy.',
  '198. 無法 wúfǎ (ú phả)Không còn cách nào.',
  '199. 房子 fángzi (pháng chự)Nhà, cái nhà.',
  '200. 衣服 yīfú (yi phú)Quần áo, trang phục.',
  '201. 聽說 tīng shuō (thing suô)Nghe nói.',
  '202. 參加 cānjiā (chan chea)Tham gia, tham dự.',
  '203. 辦法 bànfǎ (pan phả)Cách, biện pháp.',
  '204. 唯一 wéiyī (guấy yi)Duy nhất.',
  '205. 回去 huíqù (huấy chuy)Trở về, đi về.',
  '206. 人們 rénmen (rấn mân)Mọi người, người ta.',
  '207. 該死 gāisǐ (cai sử)Đáng chết, chết tiệt.',
  '208. 選擇 xuǎnzé (xoẻn chứa)Lựa chọn, tuyển chọn.',
  '209. 原因 yuányīn (doén in)Nguyên nhân.',
  '210. 下去 xiàqù (xia chuy)Xuống, đi xuống, tiếp nữa.',
  '211. 好好 hǎohǎo (háo hảo)Vui sướng , tốt đẹp.',
  '212. 確實 quèshí (chuê sứ)Xác thực, chính xác.',
  '213. 混蛋 húndàn (huấn tan)Thằng khốn, khốn nạn.',
  '214. 保證 bǎozhèng (pảo trâng)Bảo đảm.',
  '215. 學校 xuéxiào (xuế xeo)Trường học.',
  '216. 接受 jiēshòu (chiê sâu)Tiếp nhận , tiếp thu, nhận.',
  '217. 改變 gǎibiàn (cải pien)Thay đổi, sửa đổi.',
  '218. 看來 kàn lái (khan lái)Xem ra.',
  '219. 麻煩 máfan (má phán)Phiền phức, rắc rối.',
  '220. 出現 chūxiàn (chu xien)Xuất hện, hiện ra.',
  '221. 打算 dǎsuàn (tả soan)Dự định, dự kiến.',
  '222. 電影 diànyǐng (ten ỉnh)Điện ảnh, phim.',
  '223. 身上 shēnshang (sân sang)Trên cơ thể, trên người.',
  '224. 房間 fángjiān (pháng chen)Phòng, gian phòng.',
  '225. 不管 bùguǎn (pù quản)Cho dù, bất luận, mặc kệ, bỏ mặc.',
  '226. 特別 tèbié (thưa biế)Đặc biệt.',
  '227. 注意 zhùyì (tru yi)Chú ý.',
  '228. 甚至 shènzhì (sân trư)Thậm chí.',
  '229. 保護 bǎohù (pảo hu)Bảo hộ, bảo vệ.',
  '230. 真正 zhēnzhèng (trân trâng)Chân chính.',
  '231. 結果 jiéguǒ (chiế cuổ)Kết quả.',
  '232. 表現 biǎoxiàn (pẻo xien)Thể hiện, tỏ ra.',
  '233. 其實 qíshí (chí sứ)Kì thực, thực ra.',
  '234. 小心 xiǎoxīn (xẻo xin)Cẩn thận.',
  '235. 進來 jìnlái (chin lái)Gần đây, vừa qua.',
  '236. 當時 dāngshí (tang sứ)Lúc đó, khi đó, lập tức, ngay.',
  '237. 只有 zhǐyǒu (trứ yểu)Chỉ có.',
  '238. 絕對 juéduì (chuế tuây)Tuyệt đối.',
  '239. 長官 zhǎngguān (trảng quan)Quan trên, quan lớn.',
  '240. 進去 jìnqù (chin chuy)Vào (từ ngoài vào trong).',
  '241. 至少 zhìshǎo (trư sảo)Chí ít, ít nhất.',
  '242. 律師 lǜshī (lùy sư)Luật sư.',
  '243. 整個 zhěnggè (trẩng cừa)Toàn bộ, tất cả, cả thay.',
  '244. 聽到 tīng dào (thing tao)Nghe được.',
  '245. 表演 biǎoyǎn (péo dẻn)Biểu diễn.',
  '246. 正在 zhèngzài (trâng chai)Đang.',
  '247. 感到 gǎndào (cản tao)Cảm thấy, thấy.',
  '248. 那邊 nà biān (na pien)Bên kia, bên ấy.',
  '249. 故事 gùshì (cu sư)Câu chuyện.',
  '250. 結婚 jiéhūn (chiế huân)Kết hôn.',
  '251. 咱們 zánmen (chán mân)Chúng ta.',
  '252. 處理 chǔlǐ (chú lỉ)Xử lí, giải quyết.',
  '253. 妻子 qīzi (chi chự)Vợ.',
  '254. 進行 jìnxíng (chin xính)Tiến hành.',
  '255. 是否 shìfǒu (sư phẩu)Phải chăng, hay không.',
  '256. 剛剛 gānggāng (cang cang)Vừa, mới.',
  '257. 案子 ànzi (an trự)Bàn, bàn dài, vụ án, án kiện.',
  '258. 行動 xíngdòng (xính tung)Hành động.',
  '259. 第二 dì èr (ti ơ)Thứ hai( chỉ số thứ tự).',
  '260. 努力 nǔ lì (nủ li)Nỗ lực, cố gắng.',
  '261. 害怕 hàipà (hai pha)Sợ hãi, sợ sệt.',
  '262. 調查 diàochá (teo chá)Điều tra.',
  '263. 失去 shīqù (sư chuy)Mất, chết.',
  '264. 成功 chénggōng (chấng cung)Thành công.',
  '265. 考慮 kǎolǜ (khảo luy)Suy nghĩ, suy xét, cân nhắc.',
  '266. 剛才 gāngcái (cang chái)Vừa nãy.',
  '267. 約會 yuēhuì (duê huây)Hẹn hò, hẹn gặp.',
  '268. 節目 jiémù (chiế mu)Tiết mục, chương trình.',
  '269. 通過 tōngguò (thung cuô)Thông qua.',
  '270. 之間 zhī jiān (trư chen)Giữa.',
  '271. 別的 bié de (piế tơ)Cái khác.',
  '272. 開心 kāixīn (khai xin)Vui vẻ.',
  '273. 母親 mǔqīn (mủ chin)Mẹ, mẫu thân.',
  '274. 主意 zhǔyì (trủ yi)Chủ kiến , chủ định.',
  '275. 丈夫 zhàngfū (trang phu)Chồng.',
  '276. 變成 biàn chéng (pen chấng)Biến thành, trở thành.',
  '277. 解釋 jiěshì (chiể sư)Giải thích.',
  '278. 聯繫 liánxì (lén xi)Liên hệ.',
  '279. 證明 zhèngmíng (trâng mính)Chứng minh.',
  '280. 生命 shēngmìng (sâng minh)Sinh mệnh, mạng sống.',
  '281. 有點 yǒudiǎn (yếu tẻn)Có chút.',
  '282. 解決 jiějué (chiể chuế)Giải quyết.',
  '283. 難道 nándào (nán tao)Thảo nào, lẽ nào.',
  '284. 作為 zuòwéi (chuô guấy)Hành vi, làm được, với tư cách.',
  '285. 奇怪 qíguài (chí quai)Kì lạ, kì quái.',
  '286. 極了 jíle (chí lơ)Rất, cực.',
  '287. 同意 tóngyì (thúng y)Đồng ý, đồng tình.',
  '288. 遊戲 yóuxì (yếu xi)Trò chơi.',
  '289. 幫忙 bāngmáng (pang máng)Giúp đỡ.',
  '290. 危險 wéixiǎn (uấy xẻn)Nguy hiểm.',
  '291. 討厭 tǎoyàn (thảo den)Đáng ghét, ghét.',
  '292. 曾經 céngjīng (chấng ching)Trải qua, đã trải.',
  '293. 眼睛 yǎnjīng (dẻn ching) đôi mắt.',
  '294. 外面 wàimiàn (oai mien)Phía ngoài, bên ngoài.',
  '295. 國家 guójiā (cuố chea) quốc gia, đất nước.',
  '296. 總統 zǒngtǒng (chúng thủng)Tổng thống.',
  '297. 傷害 shānghài (sang hai)Tổn thương, làm hại.',
  '298. 控制 kòngzhì (khung trư)Khống chế.',
  '299. 最近 zuìjìn (chuây chin)Dạo này, gần đây.',
  '300. 聲音 shēngyīn (sâng in)Âm thanh, tiếng động.',
  '301. 快樂 kuàilè (khoai lưa)Vui vẻ.',
  '302. 可愛 kě’ài (khửa ai)Đáng yêu.',
  '303. 進入 jìnrù (chin ru)Tiến vào, bước vào, đi vào.',
  '304. 能夠 nénggòu (nấng câu)Đủ.',
  '305. 完成 wánchéng (oán chấng)Hoàn thành.',
  '306. 昨晚 zuó wǎn (chúa oản)Tối hôm qua.',
  '307. 醫院 yīyuàn (yi doen)Bệnh viện.',
  '308. 不行 bùxíng (pù xính)Không được.',
  '309. 而已 éryǐ (ớ ỷ)Mà thôi.',
  '310. 上面 shàngmiàn (sang mien)Bên trên, phía trên.',
  '311. 樣子 yàngzi (dang chự)Hình dáng, dáng vẻ.',
  '312. 有趣 yǒuqù (yểu chuy)Có hứng.',
  '313. 真的 zhēn de (trân tợ)Thật mà.',
  '314. 部分 bùfèn (pù phân)Bộ phận.',
  '315. 要求 yāoqiú (eo chiếu)Yêu cầu.',
  '316. 糟糕 zāogāo (chao cao)Hỏng bét, gay go.',
  '317. 除了 chúle (chú lờ)Ngoài ra, trừ ra.',
  '318. 容易 róngyì (rúng y)Dễ dàng, dễ.',
  '319. 保持 bǎochí (pảo chứ)Duy trì, gìn giữ.',
  '320. 雖然 suīrán (suây rán)Mặc dù.',
  '321. 想到 xiǎngdào (xẻng tao)Nghĩ đến.',
  '322. 理解 lǐjiě (lí chiể)Hiểu biết.',
  '323. 證據 zhèngjù (trâng chuy)Chứng cứ, bằng chứng.',
  '324. 簡單 jiǎndān (chẻn tan)Đơn giản.',
  '325. 不同 bùtóng (pù thúng)Không giống, không cùng.',
  '326. 夫人 fūrén (phu rấn)Phu nhân.',
  '327. 父母 fùmǔ (phu mủ)Cha mẹ.',
  '328. 事實 shìshí (sư sứ)Sự thực.',
  '329. 飛機 fēijī (phây chi)Máy bay, phi cơ.',
  '330. 家庭 jiātíng (chea thính)Gia đình.',
  '331. 秘密 mìmì (mi mi)Bí mật.',
  '332. 屍體 shītǐ (sư thỉ)Thi thể, xác chết.',
  '333. 打開 dǎkāi (tả khai)Mở ra.',
  '334. 檢查 jiǎnchá (chẻn chá)Kiểm tra.',
  '335. 早上 zǎoshang (chảo sang)Buổi sáng.',
  '336. 玩笑 wánxiào (oán xeo)Đùa.',
  '337. 任務 rènwù (rân u)Nhiệm vụ.',
  '338. 現場 xiànchǎng (xien chảng)Hiện trường.',
  '339. 博士 bóshì (puố sư)Tiến sĩ.',
  '340. 直到 zhídào (trứ tao)Mãi đến, cho đến, tận đến.',
  '341. 緊張 jǐnzhāng (chỉn trang)Lo lắng, hồi hộp.',
  '342. 簡直 jiǎnzhí (chẻn trứ)Quả là, tưởng chừng, dứt khoát.',
  '343. 放棄 fàngqì (phang chi)Bỏ cuộc, từ bỏ.',
  '344. 小子 xiǎozi (xẻo trự)Người trẻ tuổi, con trai, thằng.',
  '345. 電視 diànshì (ten sư)Ti vi, vô tuyến.',
  '346. 大概 dàgài (ta cai)Khoảng, chừng.',
  '347. 的確 díquè (tí chuê)Đích thực.',
  '348. 回到 huí dào (huấy tao)Về đến.',
  '349. 男孩 nánhái (nán hái)Con trai',
  '350. 音樂 yīnyuè (in duê)Âm nhạc',
  '351. 身體 shēntǐ (sân thỉ)Thân thể, cơ thể',
  '352. 留下 liú xià (liếu xia)Lưu lại.',
  '353. 方式 fāngshì (phang sư)Phương thức, cách thức, kiểu.',
  '354. 美元 měiyuán (mẩy doén)Đô la mỹ.',
  '355. 監獄 jiānyù (chen uy)Nhà tù, nhà giam, nhà lao.',
  '356. 這邊 zhè biān (trưa ben)Bên này.',
  '357. 重新 chóngxīn (chúng xin)Lại lần nữa, làm lại từ đầu.',
  '358. 瘋狂 fēngkuáng (phân khoáng)Điên rồ.',
  '359. 收到 shōu dào (sâu tao)Nhận được.',
  '360. 其中 qízhōng (chí trung)Trong đó.',
  '361. 想法 xiǎngfǎ (xéng phả)Cách nghĩ, ý nghĩ.',
  '362. 紐約 niǔyuē (niể duê)New york( Mỹ).',
  '363. 家裡 jiālǐ (chea lỉ)Trong nhà.',
  '364. 還要 hái yào (hái hảo)Còn muốn, vẫn muốn.',
  '365. 後面 hòumiàn (hâu men)Phía sau, đằng sau.',
  '366. 帶來 dài lái (tai lái)Đem lại.',
  '367. 昨天 zuótiān (chúa then)Hôm qua.',
  '368. 不好 bù hǎo (pù hảo)Không tốt.',
  '369. 抓住 zhuā zhù (troa tru)Bắt được , túm được.',
  '370. 記錄 jìlù (chi lu)Ghi lại , ghi chép.',
  '371. 老兄 lǎoxiōng (lảo xung)Anh bạn, ông anh.',
  '372. 來自 láizì (lái chư)Đến từ.',
  '373. 大學 dàxué (ta xuế)Đại học.',
  '374. 照顧 zhàogù (trao cu)Chăm sóc.',
  '375. 太太 tàitài (thai thai)Bà lớn, bà chủ, bà xã, bà nhà.',
  '376. 聰明 cōngmíng (chông mính)Thông minh.',
  '377. 本來 běnlái (pẩn lái)Ban đầu, trước đây, lẽ ra, đáng lẽ.',
  '378. 加油 jiāyóu (chea yếu)Cố lên.',
  '379. 多久 duōjiǔ (tuô chiểu)Bao lâu.',
  '380. 並且 bìngqiě (ping chiể)Đồng thời, hơn nữa, vả lại.',
  '381. 直接 zhíjiē (trứ chiê)Trực tiếp.',
  '382. 對於 duìyú (tuây úy)Về, đối với.',
  '383. 突然 túrán (thú rán)Đột nhiên.',
  '384. 開槍 kāi qiāng (khai cheng)Mở súng.',
  '385. 除非 chúfēi (chú phây)Trừ khi,ngoài ra.',
  '386. 正常 zhèngcháng (trâng cháng)Thường thường.',
  '387. 死亡 sǐwáng (sử oáng)Chết, tử vong.',
  '388. 終於 zhōngyú (trung úy)Cuối cùng.',
  '389. 擁有 yǒngyǒu (dúng yểu)Có.',
  '390. 不再 bù zài (pú chai)Không lặp lại , ko có lần thứ 2.',
  '391. 咖啡 kāfēi (khai phây)Cà phê.',
  '392. 阻止 zǔzhǐ (chú trử)Ngăn trở, ngăn cản',
  '393. 想像 xiǎngxiàng (xẻng xeng)Tưởng tượng.',
  '394. 冷靜 lěngjìng (lẩng ching)Vắng vẻ, yên tĩnh, bình tĩnh.',
  '395. 方法 fāngfǎ (phang phả)Phương pháp, cách làm.',
  '396. 能力 nénglì (nấng li)Năng lực, khả năng.',
  '397. 完美 wánměi (oán mẩy)Hoàn mỹ.',
  '398. 目標 mùbiāo (mu peo)Mục tiêu.',
  '399. 有關 yǒuguān (yểu quan)Liên quan, hữu quan.',
  '400. 精神 jīngshén (ching sấn)Tinh thần.',
  '401. 另外 lìngwài (ling oai)Ngoài ra.',
  '402. 放鬆 fàngsōng (phang sung)Thả lỏng, buông lỏng, lơ là.',
  '403. 休息 xiūxí (xiêu xí)Nghỉ ngơi, nghỉ.',
  '404. 每天 měitiān (mẩy then)Mỗi ngày.',
  '405. 回答 huídá (huấy tá)Trả lời, giải đáp.',
  '406. 兇手 xiōngshǒu (xung sẩu)Hung thủ.',
  '407. 負責 fùzé (phu chứa)Phụ trách.',
  '408. 介意 jièyì (chiê y)Để ý, để bụng, lưu tâm.',
  '409. 試試 shì shì (sư sư)Thử.',
  '410. 那天 nèitiā (nây then)Hôm đó.',
  '411. 系統 xìtǒng (xi thủng)Hệ thống.',
  '412. 睡覺 shuìjiào (suây cheo)Ngủ.',
  '413. 謀殺 móushā (mấu sa)Mưu sát.',
  '414. 禮物 lǐwù (lỉ u)Món quà, quà.',
  '415. 那種 nà zhǒng (na trủng)Loại đó.',
  '416. 各位 gèwèi (cưa guây)Các vị ( đại biểu, giáo viên…).',
  '417. 錯誤 cuòwù (chua u)Sai lầm, lỗi lầm, lệch lạc.',
  '418. 隨便 suíbiàn (suấy ben)Tùy tiện, tùy, tùy ý, bất cứ.',
  '419. 頭髮 tóufǎ (thấu phả)Tóc.',
  '420. 關心 guānxīn (quan xin)Quan tâm.',
  '421. 幹嗎 gànma (can ma)Làm gì.',
  '422. 興趣 xìngqù (xing chuy)Hứng thú, thích thú.',
  '423. 報告 bào gào (pao cao)Báo cáo, bản báo cáo, phát biểu.',
  '424. 從沒 cóng méi (chúng mấy)Chưa bao giờ, không bao giờ.',
  '425. 經歷 jīnglì (ching li)Từng trải, trải qua, những việc trải qua.',
  '426. 老師 lǎoshī (lảo sư)Giáo viên.',
  '427. 不用 bùyòng (bú dung)Không cần.',
  '428. 小孩 xiǎohái (xẻo hái)Trẻ em.',
  '429. 人類 rénlèi (rấn lây)Loài người, nhân loại.',
  '430. 自由 zìyóu (chư yếu)Tự do.',
  '431. 支持 zhīchí (trư chứ)Ủng hộ.',
  '432. 星期 xīngqí (xing chí)Tuần lễ, ngày thứ, chủ nhật( gọi tắt).',
  '433. 很快 hěn kuài (hẩn khoai)Rất nhanh.',
  '434. 生氣 shēngqì (sâng chi)Tức giận, giận dỗi.',
  '435. 建議 jiànyì (chien yi)Kiến nghị, đề xuất, sáng kiến.',
  '436. 做到 zuò dào (chua tao)Làm được.',
  '437. 屁股 pìgu (phi cu)Mông, đít.',
  '438. 生日 shēngrì (sâng rư)Sinh nhật , ngày sinh.',
  '439. 晚安 wǎn’ān (oản an)Ngủ ngon.',
  '440. 否則 fǒuzé (phẩu chứa)Bằng không, nếu không.',
  '441. 安排 ānpái (an phái)Sắp xếp, bố trí, trình bày.',
  '442. 年輕 niánqīng (nén ching)Tuổi trẻ, thanh niên.',
  '443. 下面 xiàmiàn (xia men)Phía dưới, bên dưới.',
  '444. 姑娘 gūniáng (cu néng)Cô nương.',
  '445. 鑰匙 yàoshi (deo sư)Chìa khóa.',
  '446. 法官 fǎguān (phả quản)Quan tòa , tòa án.',
  '447. 選手 xuǎnshǒu (xoén sẩu)Tuyển thủ, thí sinh.',
  '448. 信息 xìnxī (xin xi)Tin tức, thông tin.',
  '449. 投票 tóupiào (thấu pheo)Bỏ phiếu.',
  '450. 哥哥 gēgē (cưa cựa)Anh trai.',
  '451. 手術 shǒushù (sẩu su)P hẫu thuật.',
  '452. 必要 bìyào (pi deo)Cần thiết, thiết yếu.',
  '453. 身邊 shēnbiān (sân pen)Bên cạnh, bên mình.',
  '454. 撒謊 sāhuǎng (sa hoảng)Nói dối, bịa đặt.',
  '455. 武器 wǔqì (ủ chi)Vũ khí.',
  '456. 痛苦 tòngkǔ (thung khủ)Đau khổ, thống khổ.',
  '457. 全部 quánbù (choén pu)Toàn bộ.',
  '458. 手機 shǒujī (sẩu chi)ĐTDĐ',
  '459. 忘記 wàngjì (oang chi)Quên.',
  '460. 存在 cúnzài (chuấn chai)Tồn tại.',
  '461. 首先 shǒuxiān (sẩu xen)Đầu tiên.',
  '462. 以及 yǐjí (ỷ chí)Và, cùng.',
  '463. 個人 gèrén (cưa rấn)Cá nhân.',
  '464. 代表 dàibiǎo (tai pẻo)Đại biểu, đại diện.',
  '465. 堅持 jiānchí (chen chứ)Kiên trì.',
  '466. 意義 yìyì (yi yi)Ý nghĩa.',
  '467. 承認 chéngrèn (chấng rân)Thừa nhận.',
  '468. 發誓 fāshì (pha sư)Thề, lời thề, xin thề.',
  '469. 理由 lǐyóu (lỉ yếu)Lý do.',
  '470. 顯然 xiǎnrán (xẻn rán)Hiển nhiên.',
  '471. 政府 zhèngfǔ (trâng phủ)Chính phủ.',
  '472. 這次 zhè cì (trưa chư)Lần này.',
  '473. 生意 shēngyì (sâng y)Buôn bán,làm ăn, sức sống, nảy nở.',
  '474. 遇到 yù dào (uy tao)Gặp phải, bắt gặp.',
  '475. 即使 jíshǐ (chí sử)Cho dù, dù cho.',
  '476. 記住 jì zhù (chi tru)Ghi nhớ.',
  '477. 到處 dàochù (tao chu)Khắp nơi, mọi nơi, đâu đâu.',
  '478. 幸運 xìngyùn (xing uyn)Vận may, dịp may.',
  '479. 那時 nà shí (na sứ)Lúc đó, khi đó.',
  '480. 事兒 shì er (sư ơ)Sự việc.',
  '481. 犯罪 fànzuì (phan chuây)Phạm tội , phạm lỗi.',
  '482. 跳舞 tiàowǔ (theo ủ)Nhảy múa.',
  '483. 白痴 báichī (pái chư)Ngớ ngẩn, thằng ngốc.',
  '484. 信任 xìnrèn (xin rân)Tín nhiệm.',
  '485. 新聞 xīnwén (xin uấn)Tin tức thời sự, việc mới xảy ra.',
  '486. 未來 wèilái (guây lái)Mai sau, sau này, tương lai.',
  '487. 道歉 dàoqiàn (tao chen)Nhận lỗi, chịu lỗi.',
  '488. 可憐 kělián (khửa lén)Đáng thương.',
  '489. 實在 shízài (sứ chai)Chân thực, quả thực, thực ra.',
  '490. 加入 jiārù (chea ru)Gia nhập.',
  '491. 病人 bìngrén (ping rấn)Người bệnh.',
  '492. 治療 zhìliáo (trư léo)Trị liệu, chữa trị.',
  '493. 原諒 yuánliàng (doén leng)Tha thứ, bỏ qua.',
  '494. 行為 xíngwéi (xính guấy)Hành vi.',
  '495. 比較 bǐjiào (pỉ cheo)Tương đối.',
  '496. 婚禮 hūnlǐ (huân lỉ)Hôn lễ.',
  '497. 弟弟 dìdì (ti ti)Em trai.',
  '498. 組織 zǔzhī (chủ trư)Tổ chức.',
  '499. 想想 xiǎng xiǎng (xéng xẻng)Nghĩ .',
  '500. 繼續 jìxù (chi xuy)Tiếp tục',
]